# Generated by Django 6.0.5 on 2026-05-16 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobSeekerProfileModel',
            new_name='NeederProfileModel',
        ),
        migrations.RenameModel(
            old_name='RecruiterProfileModel',
            new_name='ProviderProfileModel',
        ),
    ]
