# Generated by Django 6.0.5 on 2026-05-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0002_rename_jobseekerprofilemodel_neederprofilemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='user_type',
            field=models.CharField(choices=[('Provider', 'Provider'), ('Needer', 'Needer')], max_length=50),
        ),
    ]
