# Generated by Django 6.0.3 on 2026-05-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0003_alter_customusermodel_user_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeederProfileModel',
            new_name='JobSeekerProfileModel',
        ),
        migrations.RenameModel(
            old_name='ProviderProfileModel',
            new_name='RecruiterProfileModel',
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='user_type',
            field=models.CharField(choices=[('Job_Seeker', 'Job_Seeker'), ('Recruiter', 'Recruiter')], max_length=50),
        ),
    ]
